class IvoryCoastLocations {
  static const List<String> cities = [
    'Abidjan',
    'Bouaké',
    'Yamoussoukro',
    'San-Pédro',
    'Korhogo',
    'Daloa',
    'Man',
    'Gagnoa',
    'Divo',
    'Soubré',
    'Grand-Bassam',
    'Dabou',
    'Anyama',
    'Bingerville',
    'Autre ville',
  ];

  static const Map<String, List<String>> communesByCity = {
    'Abidjan': [
      'Cocody',
      'Plateau',
      'Yopougon',
      'Marcory',
      'Koumassi',
      'Treichville',
      'Port-Bouët',
      'Adjamé',
      'Abobo',
      'Attécoubé',
      'Bingerville',
      'Songon',
      'Anyama',
      'Autre commune',
    ],
    'Bouaké': [
      'Commerce',
      'Air France',
      'Belle-Ville',
      'Nimbo',
      'Koko',
      'Broukro',
      'Kennedy',
      'Dar-Es-Salam',
      'Ahougnanssou',
      'Autre quartier',
    ],
    'Yamoussoukro': [
      'Assabou',
      'Morofé',
      'Habitat',
      'Dioulakro',
      'Millionnaire',
      '200 Logements',
      'Fondation',
      'Sopim',
      'N\'Zuessy',
      'Autre quartier',
    ],
    'San-Pédro': [
      'Cité',
      'Bardot',
      'Balmer',
      'Lac',
      'Séwéké',
      'Zone Industrielle',
      'Poro',
      'Autre quartier',
    ],
    'Korhogo': [
      'Koko',
      'Soba',
      'Sinistré',
      'Téguéré',
      'Haoussa',
      'Petit Paris',
      'Autre quartier',
    ],
    'Daloa': [
      'Commerce',
      'Gbeuliville',
      'Tazibouo',
      'Lobia',
      'Kennedy',
      'Huberson',
      'Autre quartier',
    ],
    'Man': [
      'Commerce',
      'Libreville',
      'Koko',
      'Domoraud',
      'Grand-Gbapleu',
      'Sari',
      'Autre quartier',
    ],
    'Grand-Bassam': [
      'France',
      'Moossou',
      'Impérial',
      'Phare',
      'Cafop',
      'Azuretti',
      'Autre quartier',
    ],
    'Gagnoa': [
      'Commerce',
      'Babré',
      'Garahio',
      'Dioulabougou',
      'Soleil',
      'Autre quartier',
    ],
    'Divo': [
      'Commerce',
      'Bada',
      'Gremian',
      'Libreville',
      'Konankro',
      'Autre quartier',
    ],
    'Soubré': [
      'Commerce',
      'Campement',
      'Gbakro',
      'Kouakoukro',
      'Autre quartier',
    ],
    'Dabou': [
      'Commerce',
      'Gbougbo',
      'Lopou',
      'Debrimou',
      'Autre quartier',
    ],
    'Bingerville': [
      'Centre-ville',
      'Gbagba',
      'Blanchon',
      'Sehia',
      'Autre quartier',
    ],
    'Anyama': [
      'Centre-ville',
      'Anyama-Adjamé',
      'Belle-Ville',
      'Schneider',
      'Autre quartier',
    ],
    'Autre ville': [
      'Centre-ville',
      'Quartier résidentiel',
      'Autre quartier',
    ],
  };

  static List<String> getCommunes(String? city) {
    if (city == null || city.isEmpty) {
      return communesByCity['Abidjan']!;
    }
    return communesByCity[city] ?? [
      'Centre-ville',
      'Quartier résidentiel',
      'Autre quartier',
    ];
  }
}
